### PR TITLE
remove prepare/consume from data column

### PR DESCRIPTION
**Pull request by justDare**
## Proposed changes

Removes data column consume/prepare methods that were breaking reading notifications created by NotificationContracts. Issue can be found here: https://github.com/verful/adonis-notifications/issues/3

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/verful/notifications/blob/master/.github/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by arthur-er** [comment]
Can you confirm that it works in sqlite?

**Comment by justDare** [comment]
Yea don't merge this, I ran a project locally and the responses are coming back as strings with sqlite, that might be an adonis issue. They should probably parse json the same no matter the driver....

Screen Shot 2022-08-12 at 5 32 12 PM

**Comment by justDare** [comment]
A work around could be applying the decorators conditionally based on the driver. Another idea is overriding columns from the user model, but I'm not good enough with mixins to figure out how to pass options to the data column from the user model composing it.

**Comment by arthur-er** [comment]
> A work around could be applying the decorators conditionally based on the driver. Another idea is overriding columns from the user model, but I'm not good enough with mixins to figure out how to pass options to the data column from the user model composing it.

I think that applying the JSON parse/stringify conditionally based on the type returned by the DB driver can solve the issue, IE:

`typeof payload === "string" ? JSON.parse(payload) : payload`

It took more time than i imagined to write tests for all databases Lucid support through

**Comment by justDare** [comment]
@arthur-er ya that'll work! Updated it.. Quick question while you're here, have you ever tried to type the data column with generics? I'd love to have that field typed to support different notification structures and was wondering if you'd be open to a PR.

So we could have a `data: T` column and you could type the notifiable mixin to `<SomeNotification | AnotherNotification>`.

**Comment by justDare** [comment]
@arthur-er this one should be ready to go unless you want anything changed, happy to make updates if you want!

**Pull request merged**
